server:
  port: 8999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      
      #currency-calculation-service
        - id: currency-calculation-service
          uri: lb://currency-calculation-service
          predicates:
            - Path=/calculation/**
            
      #currency-exchange-service
        - id: currency-exchange-service
          uri: lb://currency-exchange-service
          predicates:
            - Path=/exchange/**
      
            
  #Eureka-Server  
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
     
     #Eureka-Server static resource Rotue
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

          
            